on:

name: Package and Upload Assets on Tag

on:
  push:
    tags:
      - '*'

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create json zip
        run: |
          shopt -s globstar
          zip -r json_files.zip json/**/*.json

      - name: Create uasset zip
        run: |
          shopt -s globstar
          zip -r uasset_files.zip uasset/**/*.uasset

      - name: Create pack zip
        run: |
          zip -j pack_files.zip Pack/*.pak Pack/*.ucas Pack/*.utoc

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GH_PAT }}
          name: Release ${{ github.ref_name }}
          body: 'Release generado automáticamente por workflow.'
          draft: false
          prerelease: false
          artifacts: |
            json_files.zip
            uasset_files.zip
            pack_files.zip
